---
name: "Build"
"on":
  push:
    branches:
      - "main"
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v5"
      - uses: "actions/cache@v4"
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: "${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}"
      - name: "Build binaries in release mode"
        run: |
          cargo build --release
      - name: "Upload release artifact"
        uses: "actions/upload-artifact@v4"
        with:
          name: "lorem"
          path: "target/release/lorem"
